config/urls.py
from django.contrib import admin
from django.urls import path, include
from tweet.views import IndexView
from django.conf import settings
from django.conf.urls.static import static

# 画像を表示するためにstaticメソッドの部分を追加。
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),  # Django標準のログイン機能を使用
    path('tweet/', include('tweet.urls')),
    path('', IndexView.as_view(), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweet/urls.py
from django.urls import path
from .views import (TwtListView, TwtDetailView, TwtDeleteView, TwtCreateView,
                    TwtEditView, TwtCommentCreateView, TwtCommentDeleteView,
                    TwtCommentEditView, tweet_like, comment_like,
                    tweet_detail_like, ProfileView)


app_name = 'tweet'
urlpatterns = [
    path('list/', TwtListView.as_view(), name='twt_list'),
    path('detail/<int:pk>/', TwtDetailView.as_view(), name='twt_detail'),
    path('delete/<int:pk>/', TwtDeleteView.as_view(), name='twt_delete'),
    path('edit/<int:pk>/', TwtEditView.as_view(), name='twt_edit'),
    path('create/', TwtCreateView.as_view(), name='twt_create'),
    path('comment/create/<int:pk>/', TwtCommentCreateView.as_view(),
         name='comment_create'),
    path('comment/delete/<int:pk>/', TwtCommentDeleteView.as_view(),
         name='comment_delete'),
    path('comment/edit/<int:pk>/', TwtCommentEditView.as_view(),
         name='comment_edit'),
    path('tweet_like/', tweet_like, name='tweet_like'),
    path('comment_like/', comment_like, name='comment_like'),
    path('tweet_detail_like/', tweet_detail_like, name='tweet_detail_like'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
]

users/urls.py
from django.urls import path
from .views import (SignUpView, follow, TweetUserListView, CommentUserListView,
                    FollowerUserListView, FollowingUserListView)

app_name = 'users'
urlpatterns = [
    path('singup/', SignUpView.as_view(), name='signup'),
    path('follow/', follow, name='follow'),
    path(
        'userlist/tweet/<int:pk>/',
        TweetUserListView.as_view(),
        name='tweet_user_list'
    ),
    path(
        'userlist/comment/<int:pk>/',
        CommentUserListView.as_view(),
        name='comment_user_list'
    ),
    path(
        'userlist/follower/<int:pk>/',
        FollowerUserListView.as_view(),
        name='follower_user_list'
    ),
    path(
        'userlist/following/<int:pk>/',
        FollowingUserListView.as_view(),
        name='following_user_list'
    ),
]

tweet/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Tweet(models.Model):
    tweet = models.TextField()
    picture = models.ImageField(
        upload_to='image/picture/',
        blank=True,
        null=True
    )
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='tweet_author'
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    like = models.ManyToManyField(get_user_model(),
                                  blank=True)

    def __str__(self):
        if len(self.tweet) < 10:
            return self.tweet
        else:
            return self.tweet[:10] + '...'

    def get_absolute_url(self):
        return reverse('tweet:twt_detail', args=[str(self.id)])


class Comment(models.Model):
    tweet = models.ForeignKey(
        Tweet,
        on_delete=models.CASCADE
    )
    comment = models.TextField(max_length=255)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='comment_author'
    )
    like = models.ManyToManyField(get_user_model(),
                                  blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        if len(self.comment) < 10:
            return self.comment
        else:
            return self.comment[:10] + '...'

tweet/forms.py
from django import forms
from .models import Tweet, Comment


class TweetForm(forms.ModelForm):

    class Meta:
        model = Tweet
        fields = ('tweet', 'picture')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tweet'].required = False
        self.fields['tweet'].label = 'tweet'
        self.fields['picture'].required = False
        self.fields['picture'].label = 'upload image'

    def clean(self):
        tweet = self.cleaned_data['tweet']
        picture = self.cleaned_data['picture']

        if not (tweet or picture):
            raise forms.ValidationError(
                'Both "tweet" and "image" are blank!'
            )


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('comment',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['comment'].required = True
        self.fields['comment'].label = 'comment'

tweet/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, RedirectView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from datetime import datetime, timedelta
from .models import Tweet, Comment
from .forms import TweetForm, CommentForm
from users.models import CustomUser


# LoginRequiredMixinを先に継承することでログインしていないユーザはツイート画面を開けないようにする。
class IndexView(RedirectView):
    url = reverse_lazy('tweet:twt_list')
    login_url = 'login'


class TwtListView(ListView):
    model = Tweet
    template_name = 'tweet/twt_list.html'
    login_url = 'login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tweets = []
        tweet_list = Tweet.objects.all().order_by('-created')
        now = datetime.now()
        for tweet in tweet_list:
            tweet_time = calc_tweet_time(now, tweet.created)
            tweet_liked = False
            if tweet.like.filter(id=self.request.user.id).exists():
                tweet_liked = True
            tweets.append({
                'tweet': tweet,
                'tweet_time': tweet_time,
                'comments': Comment.objects.select_related('tweet').filter(
                    tweet__id=tweet.id).count(),
                'tweet_liked': tweet_liked
            })
        context.update({'tweets': tweets})
        return context


class TwtDetailView(DetailView):
    model = Tweet
    template_name = 'tweet/twt_detail.html'
    login_url = 'login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tweet = Tweet.objects.get(pk=self.kwargs['pk'])
        tweet_liked = False
        if tweet.like.filter(id=self.request.user.id).exists():
            tweet_liked = True
        now = datetime.now()
        tweet_time = calc_tweet_time(now, tweet.created)
        comment_list = Comment.objects.filter(tweet__id=self.kwargs['pk'])
        comments = []
        for comment in comment_list:
            comment_liked = False
            if comment.like.filter(id=self.request.user.id).exists():
                comment_liked = True
            comments.append({
                'comment': comment,
                'comment_liked': comment_liked,
            })
        context.update({
            'comments': comments,
            'tweet': tweet,
            'tweet_time': tweet_time,
            'tweet_liked': tweet_liked,
        })
        return context


class TwtCreateView(LoginRequiredMixin, CreateView):
    model = Tweet
    template_name = 'tweet/twt_create.html'
    fields = ['tweet', 'picture']
    login_url = 'login'
    success_url = reverse_lazy('tweet:twt_list')

    def post(self, *args, **kwargs):
        form = TweetForm(self.request.POST, self.request.FILES)
        is_valid = form.is_valid()
        if not is_valid:
            return render(self.request, 'twt_create.html', {'form': form})
        form.instance.author = self.request.user
        form.save()
        return redirect(reverse_lazy('tweet:twt_detail',
                                     args=(form.instance.id,)))


# UserPassesTestMixinを継承することで、投稿の編集は投稿者のみがすることができるようになる。
class TwtEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Tweet
    template_name = 'tweet/twt_edit.html'
    fields = ['tweet', 'picture']
    login_url = 'login'

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class TwtDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Tweet
    template_name = 'tweet/twt_delete.html'
    success_url = reverse_lazy('tweet:twt_list')

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tweet = Tweet.objects.get(pk=self.kwargs['pk'])
        context.update({'tweet': tweet})
        return context


class TwtCommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'tweet/comment_create.html'
    fields = ['comment']
    login_url = 'login'
    # 上にツイートはあるが、表示はコメント部分が一番上に表示されるように最初からスクロールされた状態で表示する。

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tweet = Tweet.objects.get(pk=self.kwargs['pk'])
        context.update({
            'tweet': tweet,
        })
        return context

    def post(self, *args, **kwargs):
        form = CommentForm(self.request.POST)
        is_valid = form.is_valid()
        if not is_valid:
            return render(self.request, 'tweet/comment_create.html',
                          {'form': form})
        form.instance.tweet = Tweet.objects.get(pk=self.kwargs['pk'])
        form.instance.author = self.request.user
        form.save()
        return redirect(reverse_lazy('tweet:twt_detail',
                                     args=(form.instance.tweet_id,)))


class TwtCommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = 'tweet/comment_delete.html'

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment = Comment.objects.get(pk=self.kwargs['pk'])
        context.update({
            'comment': comment,
            'tweet': Tweet.objects.get(
                id=comment.tweet.id),
        })
        return context

    def get_success_url(self, **kwargs):
        comment = Comment.objects.get(pk=self.kwargs['pk'])
        return reverse_lazy('tweet:twt_detail',
                            kwargs={'pk': comment.tweet.id})


class TwtCommentEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    template_name = 'tweet/comment_edit.html'
    fields = ['comment']
    login_url = 'login'
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment = Comment.objects.get(pk=self.kwargs['pk'])
        context.update({
            'comment': comment,
            'tweet': Tweet.objects.get(
                id=comment.tweet.id),
        })
        return context

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

    def get_success_url(self, **kwargs):
        comment = Comment.objects.get(pk=self.kwargs['pk'])
        return reverse_lazy('tweet:twt_detail',
                            kwargs={'pk': comment.tweet.id})


class ProfileView(ListView):
    model = Tweet
    template_name = 'tweet/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile_user = CustomUser.objects.get(id=self.kwargs['pk'])
        follower_count = profile_user.followers.all().count()
        following_count = profile_user.followees.all().count()
        is_follow = False
        if profile_user.followers.filter(id=self.request.user.id).exists():
            is_follow = True
        tweets = []
        tweet_list = Tweet.objects.filter(
            author_id=self.kwargs['pk']).order_by('-created')
        now = datetime.now()
        for tweet in tweet_list:
            tweet_time = calc_tweet_time(now, tweet.created)
            tweet_liked = False
            if tweet.like.filter(id=self.request.user.id).exists():
                tweet_liked = True
            tweets.append({
                'tweet': tweet,
                'tweet_time': tweet_time,
                'comments': Comment.objects.select_related('tweet').filter(
                    tweet__id=tweet.id).count(),
                'tweet_liked': tweet_liked
            })
        context.update({
            'tweets': tweets,
            'profile_user': profile_user,
            'is_follow': is_follow,
            'follower_count': follower_count,
            'following_count': following_count,
        })
        return context


# ブラウザバックでいいねの挙動がおかしくなる。ハートのオンオフが逆になる。またはいいね数が逆になる。
def tweet_like(request):
    if request.user.is_authenticated:
        tweet = Tweet.objects.get(id=request.POST.get('tweet_id'))
        tweet_like = False
        if tweet.like.filter(id=request.user.id).exists():
            tweet.like.remove(request.user)
            tweet_like = False
        else:
            tweet.like.add(request.user)
            tweet_like = True
        like_count = tweet.like.count()
        json_data = {
            'like_count': like_count,
            'tweet_like': tweet_like,
        }
        return JsonResponse(json_data)
    else:
        return HttpResponse(reverse_lazy('login'))


def comment_like(request):
    if request.user.is_authenticated:
        comment = Comment.objects.get(id=request.POST.get('comment_id'))
        if comment.like.filter(id=request.user.id).exists():
            comment.like.remove(request.user)
        else:
            comment.like.add(request.user)
        comment_like_count = comment.like.count()
        json_data = {
            'comment_like_count': comment_like_count
        }
        return JsonResponse(json_data)
    else:
        return HttpResponse(reverse_lazy('login'))


def tweet_detail_like(request):
    if request.user.is_authenticated:
        tweet = Tweet.objects.get(id=request.POST.get('tweet_id'))
        if tweet.like.filter(id=request.user.id).exists():
            tweet.like.remove(request.user)
        else:
            tweet.like.add(request.user)
        like_count = tweet.like.count()
        json_data = {
            'detail_like_count': like_count
        }
        return JsonResponse(json_data)
    else:
        return HttpResponse(reverse_lazy('login'))

templates/tweet/comment_create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Create Comment{% endblock title %}

{% block content %}
<div class="profile">
    <a href="">
        {% if tweet.author.icon %}
            <!-- プロフィール画面に飛ぶリンクを追加する -->
            <img class="icon" src="{{ tweet.author.icon.url }}">
        {% else %}
            <img class="icon" src="{% static 'image/icon/noimage.png' %}">
        {% endif %}
    </a>
    <a class="username" href="">{{ tweet.author.username }}</a>
</div>
<div class="tweet-detail">
    <p class="tweet-text">{{ tweet.tweet }}</p>
    {% if tweet.picture %}
        <p class="tweetpicture"><img src="{{ tweet.picture.url }}" width="380"></p>
    {% endif %}
    <p class="gray-char">{{ tweet.created|date:"Y/m/j H:i:s"}}</p>
</div>
<div class="partition-line"></div>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Comment" class="btn btn-primary">
</form>
{% endblock content %}

templates/tweet/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Profile{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/twt.css' %}">
{% endblock css %}

{% block content %}
<div class="profile-header">
{% if profile_user.icon %}
    <img class="big-icon profile-icon" src="{{ profile_user.icon.url }}">
{% else %}
    <img class="big-icon profile-icon" src="{% static 'image/icon/noimage.png' %}">
{% endif %}
{% if profile_user != user %}
    {% if is_follow %}
        <button id="following-id" type="button" class="btn btn-primary follow-btn" name="user_id" value="{{ profile_user.id }}" data-href="{% url 'users:follow' %}">Following</button>
        <button id="follow-id" type="button" class="btn btn-primary follow-btn follow-hide" name="user_id" value="{{ profile_user.id }}" data-href="{% url 'users:follow' %}">Follow</button>
    {% else %}
        <button id="following-id" type="button" class="btn btn-primary follow-btn following-hide" name="user_id" value="{{ profile_user.id }}" data-href="{% url 'users:follow' %}">Following</button>
        <button id="follow-id" type="button" class="btn btn-primary follow-btn" name="user_id" value="{{ profile_user.id }}" data-href="{% url 'users:follow' %}">Follow</button>
    {% endif %}
{% endif %}
</div>

<p class="profile-name">{{ profile_user.username }}</p>
{% if profile_user.age %}
    <p class="profile-age">Age: {{ profile_user.age }}</p>
{% else %}
    <p class="profile-age">Age: Secret</p>
{% endif %}

<a class="follow-count" href="{% url 'users:following_user_list' profile_user.id %}">{{ following_count }}</a> <span class="gray-char"> Following</span>
<a id="follower-count" class="follow-count" href="{% url 'users:follower_user_list' profile_user.id %}">{{ follower_count }}</a> <span id="follower" class="gray-char"> Follower{{ follower_count|pluralize }}</span>

{% include 'tweet/tweet.html' %}

{% endblock content %}
{% block script %}
<script type="text/javascript" src="{% static 'js/ajaxSetup.js' %}"></script>
<script type="text/javascript" src="{% static 'js/twt_list.js' %}"></script>
<script type="text/javascript" src="{% static 'js/profile.js' %}"></script>
{% endblock script %}

templates/tweet/tweet.html
{% load static %}


<div class="partition-line"></div>
{% for tweet in tweets %}
    <div class="tweetblock">
        <a class="tweet-area" href="{% url 'tweet:twt_detail' tweet.tweet.pk %}"></a>
        <div class="tweetdiv">
            <!-- プロフィール画面に飛ぶ -->
            <a class="inlink" href="{% url 'tweet:profile' tweet.tweet.author.id %}">
                {% if tweet.tweet.author.icon %}
                    <img class="icon" src="{{ tweet.tweet.author.icon.url }}">
                {% else %}
                    <img class="icon" src="{% static 'image/icon/noimage.png' %}">
                {% endif %}
            </a>
        </div>
        <div class="tweetdiv tweet-content">
            <div class="block-upper">
                <div class="username"><a class="inlink" href="{% url 'tweet:profile' tweet.tweet.author.id %}">{{ tweet.tweet.author.username }}</a></div>
                {% if user == tweet.tweet.author %}
                <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item small-char" href="{% url 'tweet:twt_edit' tweet.tweet.id %}">Edit</a>
                        <a class="dropdown-item small-char" href="{% url 'tweet:twt_delete' tweet.tweet.id %}">Delete</a>
                    </div>
                </div>
                {% endif %}
            </div>
            <p class="tweet-text">{{ tweet.tweet.tweet }}</p>
            {% if tweet.tweet.picture %}
                <p class="tweetpicture"><img src="{{ tweet.tweet.picture.url }}" width="300"></p>
            {% endif %}
            <!-- コメント入力画面に飛ぶ -->
            <div class="comment-like">
                <div>
                    <a class="inlink comment_icon" href="{% url 'tweet:comment_create' tweet.tweet.pk %}"><img class="comment-image" src="{% static 'image/comment.png' %}">{{ tweet.comments }}</a>
                </div>
                <div class="like-area">
                    <div>
                        {% if tweet.tweet_liked %}
                            <button type="submit" name="tweet_id" value="{{tweet.tweet.id}}" class="btn like-btn" data-href="{% url 'tweet:tweet_like' %}">
                                <img id="tweet-like-{{tweet.tweet.id}}" class="like-image" src="{% static 'image/heart.png' %}">
                                <img id="tweet-not-like-{{tweet.tweet.id}}" class="like-image hide-heart_blank" src="{% static 'image/heart_blank.png' %}">
                            </button>
                        {% else %}
                            <button type="submit" name="tweet_id" value="{{tweet.tweet.id}}" class="btn like-btn" data-href="{% url 'tweet:tweet_like' %}">
                                <img id="tweet-like-{{tweet.tweet.id}}" class="like-image hide-heart" src="{% static 'image/heart.png' %}">
                                <img id="tweet-not-like-{{tweet.tweet.id}}" class="like-image" src="{% static 'image/heart_blank.png' %}">
                            </button>
                        {% endif %}
                    </div>
                    <a id="tweet-like-count-{{tweet.tweet.id}}" class="like-count" href="#">{{ tweet.tweet.like.count }}</a>
                </div>
            </div>
            <p class="gray-char">{{ tweet.tweet_time }}</p>
        </div>
    </div>
    <div class="partition-line"></div>
{% endfor %}

templates/tweet/twt_create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Create Tweet{% endblock title %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Tweet" class="btn btn-primary">
</form>
{% endblock content %}

templates/tweet/twt_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Tweet Detail{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/twt.css' %}">
<link rel="stylesheet" href="{% static 'css/twt_detail.css' %}">
{% endblock css %}

{% block content %}
<div class="tweetblock">
    <div class="tweetdiv tweet-content">
        <div class="block-upper">
            <div class="profile">
                <!-- プロフィール画面に飛ぶリンクを追加する -->
                <a href="">
                    {% if tweet.author.icon %}
                        <img class="icon" src="{{ tweet.author.icon.url }}">
                    {% else %}
                        <img class="icon" src="{% static 'image/icon/noimage.png' %}">
                    {% endif %}
                </a>
                <a class="username" href="">{{ tweet.author.username }}</a>
            </div>
            {% if user == tweet.author %}
                <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item small-char" href="{% url 'tweet:twt_edit' tweet.id %}">Edit</a>
                        <a class="dropdown-item small-char" href="{% url 'tweet:twt_delete' tweet.id %}">Delete</a>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="tweet-detail">
            <p class="tweet-text">{{ tweet.tweet }}</p>
            {% if tweet.picture %}
                <p class="tweetpicture"><img src="{{ tweet.picture.url }}" width="380"></p>
            {% endif %}
            <p class="tweettime">{{ tweet.created|date:"Y/m/j H:i:s"}}</p>
            <span id="tweet-detail-like">{{ tweet.like.count }}件のいいね！</span>
            <div>
                <a class="inlink" href="{% url 'tweet:comment_create' tweet.id %}"><img class="comment-image" src="{% static 'image/comment.png' %}"></a>
                {% if tweet_liked %}
                    <button type="submit" name="tweet_id" value="{{tweet.id}}" class="btn detail-like-btn" data-href="{% url 'tweet:tweet_detail_like' %}">
                        <img id="detail-like" class="like-image" src="{% static 'image/heart.png' %}">
                        <img id="detail-not-like" class="like-image hide-heart_blank" src="{% static 'image/heart_blank.png' %}">
                    </button>
                {% else %}
                    <button type="submit" name="tweet_id" value="{{tweet.id}}" class="btn detail-like-btn" data-href="{% url 'tweet:tweet_detail_like' %}">
                        <img id="detail-like" class="like-image hide-heart" src="{% static 'image/heart.png' %}">
                        <img id="detail-not-like" class="like-image" src="{% static 'image/heart_blank.png' %}">
                    </button>
                {% endif %}
            </div>
            <div class="partition-line"></div>
        </div>
    </div>
</div>
    {% for comment in comments %}
        <div class="tweetblock">
            <div class="tweetdiv">
                <!-- プロフィール画面に飛ぶ -->
                <a class="inlink" href="">
                    {% if comment.author.icon %}
                        <img class="icon" src="{{ comment.comment.author.icon.url }}">
                    {% else %}
                        <img class="icon" src="{% static 'image/icon/noimage.png' %}">
                    {% endif %}
                </a>
            </div>
            <div class="tweetdiv tweet-content">
                <div class="block-upper">
                    <div class="username">{{ comment.comment.author.username }}</div>
                    {% if user == comment.comment.author %}
                    <div class="btn-group">
                        <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item small-char" href="{% url 'tweet:comment_edit' comment.comment.pk %}">Edit</a>
                            <a class="dropdown-item small-char" href="{% url 'tweet:comment_delete' comment.comment.pk %}">Delete</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
                <p class="tweet-text">{{ comment.comment.comment }}</p>
                <p class="gray-char">{{ comment.comment.created|date:"Y/m/j H:i:s" }}</p>
                <div class="like-area">
                    <div>
                        {% if comment.comment_liked %}
                            <button type="submit" name="comment_id" value="{{comment.comment.id}}" class="btn like-btn" data-href="{% url 'tweet:comment_like' %}">
                                <img id="comment-like-{{comment.comment.id}}" class="like-image" src="{% static 'image/heart.png' %}">
                                <img id="comment-not-like-{{comment.comment.id}}" class="like-image hide-heart_blank" src="{% static 'image/heart_blank.png' %}">
                            </button>
                        {% else %}
                            <button type="submit" name="comment_id" value="{{comment.comment.id}}" class="btn like-btn" data-href="{% url 'tweet:comment_like' %}">
                                <img id="comment-like-{{comment.comment.id}}" class="like-image hide-heart" src="{% static 'image/heart.png' %}">
                                <img id="comment-not-like-{{comment.comment.id}}" class="like-image" src="{% static 'image/heart_blank.png' %}">
                            </button>
                        {% endif %}
                    </div>
                    <a id="comment-like-count-{{comment.comment.id}}" class="like-count" href="#">{{ comment.comment.like.count }}</a>
                </div>
            </div>
        </div>
        <div class="partition-line"></div>
    {% endfor %}
{% endblock content %}
{% block script %}
<script type="text/javascript" src="{% static 'js/ajaxSetup.js' %}"></script>
<script type="text/javascript" src="{% static 'js/twt_detail.js' %}"></script>
{% endblock script %}

templates/tweet/twt_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Tweet List{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/twt.css' %}">
{% endblock css %}

{% block content %}
<h1>Tweet</h1>
<div class="create-tweet"><a href="{% url 'tweet:twt_create' %}"><img class="icon" src="{% static 'image/pencil.png' %}"></a></div>
{% include 'tweet/tweet.html' %}

{% endblock content %}
{% block script %}
<script type="text/javascript" src="{% static 'js/ajaxSetup.js' %}"></script>
<script type="text/javascript" src="{% static 'js/twt_list.js' %}"></script>
{% endblock script %}