config/urls.py
from django.contrib import admin
from django.urls import path, include
from tweet.views import IndexView
from django.conf import settings
from django.conf.urls.static import static

# 画像を表示するためにstaticメソッドの部分を追加。
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),  # Django標準のログイン機能を使用
    path('tweet/', include('tweet.urls')),
    path('', IndexView.as_view(), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweet/urls.py
from django.urls import path
from .views import (TwtListView, TwtDetailView, TwtDeleteView, TwtCreateView,
                    TwtEditView, TwtCommentCreateView, TwtCommentDeleteView,
                    TwtCommentEditView, tweet_like, comment_like,
                    tweet_detail_like, ProfileView)


app_name = 'tweet'
urlpatterns = [
    path('list/', TwtListView.as_view(), name='twt_list'),
    path('detail/<int:pk>/', TwtDetailView.as_view(), name='twt_detail'),
    path('delete/<int:pk>/', TwtDeleteView.as_view(), name='twt_delete'),
    path('edit/<int:pk>/', TwtEditView.as_view(), name='twt_edit'),
    path('create/', TwtCreateView.as_view(), name='twt_create'),
    path('comment/create/<int:pk>/', TwtCommentCreateView.as_view(),
         name='comment_create'),
    path('comment/delete/<int:pk>/', TwtCommentDeleteView.as_view(),
         name='comment_delete'),
    path('comment/edit/<int:pk>/', TwtCommentEditView.as_view(),
         name='comment_edit'),
    path('tweet_like/', tweet_like, name='tweet_like'),
    path('comment_like/', comment_like, name='comment_like'),
    path('tweet_detail_like/', tweet_detail_like, name='tweet_detail_like'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
]

users/urls.py
from django.urls import path
from .views import (SignUpView, follow, TweetUserListView, CommentUserListView,
                    FollowerUserListView, FollowingUserListView)

app_name = 'users'
urlpatterns = [
    path('singup/', SignUpView.as_view(), name='signup'),
    path('follow/', follow, name='follow'),
    path(
        'userlist/tweet/<int:pk>/',
        TweetUserListView.as_view(),
        name='tweet_user_list'
    ),
    path(
        'userlist/comment/<int:pk>/',
        CommentUserListView.as_view(),
        name='comment_user_list'
    ),
    path(
        'userlist/follower/<int:pk>/',
        FollowerUserListView.as_view(),
        name='follower_user_list'
    ),
    path(
        'userlist/following/<int:pk>/',
        FollowingUserListView.as_view(),
        name='following_user_list'
    ),
]

templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block css %}
    {% endblock css %}
  </head>
  <body>
    {% block header %}
    <div class="header-container">
      <!-- ヘッダには左端にプロフィール画面へのリンクを表示、中央には画面の一番上に行くリンクを表示するよう修正する。 -->
      {% if user.is_authenticated %}
      <div class="header-tweet">
        <div>
          <a href="{% url 'tweet:profile' user.id %}">
          {% if user.icon %}
            <img class="mini-icon" src="{{ user.icon.url }}">
          {% else %}
            <img class="mini-icon" src="{% static 'image/icon/noimage.png' %}">
          {% endif %}
          </a>
        </div>
        <div><a href="{% url 'tweet:twt_list' %}"><img class="icon" src="{% static 'image/pigeon.jpg' %}"></a></div>
        <div><a class="btn btn-dark" href="{% url 'logout' %}">Log out</a></div>
      </div>
      {% else %}
      <div class="header-tweet">
        <div></div>
        <div><a href="{% url 'tweet:twt_list' %}"><img class="icon" src="{% static 'image/pigeon.jpg' %}"></a></div>
        <div>
          <span><a class="btn btn-light" href="{% url 'login' %}">LogIn</a></span>
          <span><a class="btn btn-info" href="{% url 'users:signup' %}">SignUp</a></span>
        </div>
      </div>
      {% endif %}
    </div>
    {% endblock header %}
    <div class="content-block">
      {% block content %} {% endblock content %}
    </div>
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
      integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% block script %}{% endblock script %}
  </body>
</html>